openapi: "3.0.0"
info:
  version: 1.0.0
  title: Mines - address app
  license:
    name: MIT
servers:
  - url: http://someUrl/v1
paths:
  /town:
    get:
      summary: List all towns
      operationId: list_town
      tags:
        - town
      responses:
        '200':
          description: An array of towns
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Town'
    post:
      summary: Create a town
      operationId: create_town
      tags:
        - town
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Town'
      responses:
        '201':
          description: Null response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Town'
    put:
      summary: Update a town
      operationId: update_town
      tags:
        - town
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Town'
      responses:
        '200':
          description: Null response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Town'
  /town/{id}:
    get:
      summary: Info for a specific town
      operationId: get_town_id
      tags:
        - town
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the town to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Town"
    delete:
      tags:
        - town
      summary: Delete a town.
      operationId: delete_town
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '204':
          description: Town has been deleted.
          content:
            application/json:
              schema:
                type: string
                description: ID of the deleted entity.

  /address:
    get:
      summary: List all address
      operationId: list_address
      tags:
        - address
      responses:
        '200':
          description: An array of address
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Address'
    post:
      summary: Create an address
      operationId: create_address
      tags:
        - address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
      responses:
        '201':
          description: Null response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
    put:
      summary: Update an address
      operationId: update_address
      tags:
        - address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
      responses:
        '200':
          description: Null response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
  /address/{id}:
    get:
      summary: Info for a specific address
      operationId: get_address_id
      tags:
        - address
      parameters:
        -
          name: id
          in: path
          required: true
          description: The id of the address to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Address"
    delete:
      tags:
        - address
      summary: Delete a address.
      operationId: delete_address
      parameters:
        -
          in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '204':
          description: Address has been deleted.
          content:
            application/json:
              schema:
                type: string
                description: ID of the deleted entity.

components:
  schemas:
    Town:
      required:
        - name
        - postCode
      properties:
        id:
          type: string
        name:
          type: string
        postCode:
          type: string
    Target:
      required:
        - firstname
        - name
        - phoneNumber
        - addresses
      properties:
        id:
          type: string
        firstname:
          type: string
        name:
          type: string
        phoneNumber:
          type: object
        addresses:
          type: array
          additionalProperties: false
          items:
            type: string
    Address:
      required:
        - number
        - street
        - town
        - targets
      properties:
        number:
          type: integer
        street:
          type: string
        town:
          type: object
        targets:
          type: array
          additionalProperties: false
          items:
            type: object
    PhoneNumber:
      required:
        - phoneNumber
      properties:
        phoneNumber:
          type: string